# Generated by Django 3.0.6 on 2020-05-19 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('component_name', models.CharField(max_length=200)),
                ('component_description', models.TextField()),
                ('component_price', models.FloatField()),
                ('component_stock', models.IntegerField()),
                ('component_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.ComponentCategory')),
            ],
        ),
    ]
