# Generated by Django 3.0.6 on 2020-05-19 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='component_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='component_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='component_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='component_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='component_stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='componentcategory',
            old_name='category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='componentcategory',
            old_name='category_name',
            new_name='name',
        ),
    ]
