# Generated by Django 3.0.6 on 2020-05-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20200518_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='componentcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
