# Generated by Django 3.0.6 on 2020-05-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20200518_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentcategory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
