# Generated by Django 3.0.6 on 2020-05-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20200518_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterModelOptions(
            name='componentcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
