# Generated by Django 3.0.6 on 2020-05-21 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_auto_20200520_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='component_category',
        ),
        migrations.AddField(
            model_name='componentcategory',
            name='component',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='components.Component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='component',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
