# Generated by Django 3.0.6 on 2020-05-21 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20200520_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentcategory',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Component'),
        ),
    ]
