# Generated by Django 3.0.6 on 2020-05-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_auto_20200520_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentcategory',
            name='component',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='ComponentCategory',
        ),
    ]
