# Generated by Django 3.0.6 on 2020-05-21 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_component_componentcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentcategory',
            name='component',
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='components.ComponentCategory'),
        ),
    ]
